registration:
    path: /registration
    methods: GET|POST
    controller: App\UserInterface\Controller\RegistrationController

home:
    path: /
    methods: GET
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: home.html.twig
