### ADMINISTRATOR ###
user_listing:
    path: /dashboard/administrator/users
    methods: GET
    controller: App\UserInterface\Controller\Security\User\ListingController

user_update:
    path: /dashboard/administrator/users/{id}/update
    methods: GET|POST
    controller: App\UserInterface\Controller\Security\User\UpdateController

product_create:
    path: /dashboard/administrator/shop/products/create
    methods: GET|POST
    controller: App\UserInterface\Controller\Shop\Product\CreateController

product_update:
    path: /dashboard/administrator/shop/products/{id}/update
    methods: GET|POST
    controller: App\UserInterface\Controller\Shop\Product\UpdateController

product_remove:
    path: /dashboard/administrator/shop/products/{id}/remove
    methods: GET
    controller: App\UserInterface\Controller\Shop\Product\RemoveController

product_listing:
    path: /dashboard/administrator/shop/products
    methods: GET
    controller: App\UserInterface\Controller\Shop\Product\ListingController

newsletter_send:
    path: /dashboard/administrator/newsletter/send
    methods: GET|POST
    controller: App\UserInterface\Controller\Newsletter\SendController

### REDACTOR ###
article_create:
    path: /dashboard/redactor/articles/create
    methods: GET|POST
    controller: App\UserInterface\Controller\Article\CreateController

article_update:
    path: /dashboard/redactor/articles/{id}/update
    methods: GET|POST
    controller: App\UserInterface\Controller\Article\UpdateController

article_listing:
    path: /dashboard/redactor/articles
    methods: GET
    controller: App\UserInterface\Controller\Article\ListingController

article_remove:
    path: /dashboard/redactor/articles/{id}/remove
    methods: GET
    controller: App\UserInterface\Controller\Article\RemoveController

article_show:
    path: /article/{id}/show
    methods: GET
    controller: App\UserInterface\Controller\Article\ShowController

category_create:
    path: /dashboard/redactor/categories/create
    methods: GET|POST
    controller: App\UserInterface\Controller\Category\CreateController

category_update:
    path: /dashboard/redactor/categories/{id}/update
    methods: GET|POST
    controller: App\UserInterface\Controller\Category\UpdateController

category_listing:
    path: /dashboard/redactor/categories
    methods: GET
    controller: App\UserInterface\Controller\Category\ListingController

category_remove:
    path: /dashboard/redactor/categories/{id}/remove
    methods: GET
    controller: App\UserInterface\Controller\Category\RemoveController

### USER ###
logout:
    path: /user/logout
    methods: GET
    controller: App\UserInterface\Controller\LogoutController

user_profile_update:
    path: /user/{id}/profile
    methods: GET|POST
    controller: App\UserInterface\Controller\Security\User\Profile\UpdateController

### ANONYMOUS ###

registration:
    path: /registration
    methods: GET|POST
    controller: App\UserInterface\Controller\RegistrationController

login:
    path: /login
    methods: GET|POST
    controller: App\UserInterface\Controller\LoginController

ask_password_reset:
    path: /reset-password
    methods: GET|POST
    controller: App\UserInterface\Controller\Security\AskPasswordResetController

recover_password:
    path: /handle-reset-password/{email}/{token}
    methods: GET|POST
    controller: App\UserInterface\Controller\Security\RecoverPasswordController

ticket_send:
    path: /contact
    methods: GET|POST
    controller: App\UserInterface\Controller\Ticket\SendController

### ALL ###

home:
    path: /
    methods: GET
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: home.html.twig