registration:
    path: /registration
    methods: GET|POST
    controller: App\UserInterface\Controller\RegistrationController

login:
    path: /login
    methods: GET|POST
    controller: App\UserInterface\Controller\LoginController

article_create:
    path: /articles/create
    methods: GET|POST
    controller: App\UserInterface\Controller\Article\CreateController

category_create:
    path: /categories/create
    methods: GET|POST
    controller: App\UserInterface\Controller\Category\CreateController

logout:
    path: /logout
    methods: GET
    controller: App\UserInterface\Controller\LogoutController

home:
    path: /
    methods: GET
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: home.html.twig
