<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJWk0qqm\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJWk0qqm/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerJWk0qqm.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerJWk0qqm\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerJWk0qqm\App_KernelTestDebugContainer([
    'container.build_hash' => 'JWk0qqm',
    'container.build_id' => 'eefb1a0e',
    'container.build_time' => 1609419445,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJWk0qqm');
