<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'article_create' => [[], ['_controller' => 'App\\UserInterface\\Controller\\Article\\CreateController'], [], [['text', '/articles/create']], [], []],
    'article_update' => [['id'], ['_controller' => 'App\\UserInterface\\Controller\\Article\\UpdateController'], [], [['text', '/update'], ['variable', '/', '[^/]++', 'id', true], ['text', '/articles']], [], []],
    'article_listing' => [[], ['_controller' => 'App\\UserInterface\\Controller\\Article\\ListingController'], [], [['text', '/articles']], [], []],
    'article_remove' => [['id'], ['_controller' => 'App\\UserInterface\\Controller\\Article\\RemoveController'], [], [['text', '/remove'], ['variable', '/', '[^/]++', 'id', true], ['text', '/articles']], [], []],
    'category_create' => [[], ['_controller' => 'App\\UserInterface\\Controller\\Category\\CreateController'], [], [['text', '/categories/create']], [], []],
    'category_update' => [['id'], ['_controller' => 'App\\UserInterface\\Controller\\Category\\UpdateController'], [], [['text', '/update'], ['variable', '/', '[^/]++', 'id', true], ['text', '/categories']], [], []],
    'category_listing' => [[], ['_controller' => 'App\\UserInterface\\Controller\\Category\\ListingController'], [], [['text', '/categories']], [], []],
    'category_remove' => [['id'], ['_controller' => 'App\\UserInterface\\Controller\\Category\\RemoveController'], [], [['text', '/remove'], ['variable', '/', '[^/]++', 'id', true], ['text', '/categories']], [], []],
    'registration' => [[], ['_controller' => 'App\\UserInterface\\Controller\\RegistrationController'], [], [['text', '/registration']], [], []],
    'login' => [[], ['_controller' => 'App\\UserInterface\\Controller\\LoginController'], [], [['text', '/login']], [], []],
    'ask_password_reset' => [[], ['_controller' => 'App\\UserInterface\\Controller\\Security\\AskPasswordResetController'], [], [['text', '/reset-password']], [], []],
    'recover_password' => [['email', 'token'], ['_controller' => 'App\\UserInterface\\Controller\\Security\\RecoverPasswordController'], [], [['variable', '/', '[^/]++', 'token', true], ['variable', '/', '[^/]++', 'email', true], ['text', '/handle-reset-password']], [], []],
    'logout' => [[], ['_controller' => 'App\\UserInterface\\Controller\\LogoutController'], [], [['text', '/logout']], [], []],
    'role_create' => [[], ['_controller' => 'App\\UserInterface\\Controller\\Security\\Role\\CreateController'], [], [['text', '/dashboard/role/create']], [], []],
    'user_listing' => [[], ['_controller' => 'App\\UserInterface\\Controller\\Security\\User\\ListingController'], [], [['text', '/dashboard/users']], [], []],
    'home' => [[], ['template' => 'home.html.twig', '_controller' => 'Symfony\\Bundle\\FrameworkBundle\\Controller\\TemplateController'], [], [['text', '/']], [], []],
];
