<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIxuC3xm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIxuC3xm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIxuC3xm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIxuC3xm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIxuC3xm\App_KernelDevDebugContainer([
    'container.build_hash' => 'IxuC3xm',
    'container.build_id' => '419f5259',
    'container.build_time' => 1609418151,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIxuC3xm');
