<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'article_create' => [[], ['_controller' => 'App\\UserInterface\\Controller\\Article\\CreateController'], [], [['text', '/articles/create']], [], []],
    'article_update' => [['id'], ['_controller' => 'App\\UserInterface\\Controller\\Article\\UpdateController'], [], [['text', '/update'], ['variable', '/', '[^/]++', 'id', true], ['text', '/articles']], [], []],
    'article_listing' => [[], ['_controller' => 'App\\UserInterface\\Controller\\Article\\ListingController'], [], [['text', '/articles']], [], []],
    'article_remove' => [['id'], ['_controller' => 'App\\UserInterface\\Controller\\Article\\RemoveController'], [], [['text', '/remove'], ['variable', '/', '[^/]++', 'id', true], ['text', '/articles']], [], []],
    'category_create' => [[], ['_controller' => 'App\\UserInterface\\Controller\\Category\\CreateController'], [], [['text', '/categories/create']], [], []],
    'category_update' => [['id'], ['_controller' => 'App\\UserInterface\\Controller\\Category\\UpdateController'], [], [['text', '/update'], ['variable', '/', '[^/]++', 'id', true], ['text', '/categories']], [], []],
    'category_listing' => [[], ['_controller' => 'App\\UserInterface\\Controller\\Category\\ListingController'], [], [['text', '/categories']], [], []],
    'category_remove' => [['id'], ['_controller' => 'App\\UserInterface\\Controller\\Category\\RemoveController'], [], [['text', '/remove'], ['variable', '/', '[^/]++', 'id', true], ['text', '/categories']], [], []],
    'registration' => [[], ['_controller' => 'App\\UserInterface\\Controller\\RegistrationController'], [], [['text', '/registration']], [], []],
    'login' => [[], ['_controller' => 'App\\UserInterface\\Controller\\LoginController'], [], [['text', '/login']], [], []],
    'ask_password_reset' => [[], ['_controller' => 'App\\UserInterface\\Controller\\Security\\AskPasswordResetController'], [], [['text', '/reset-password']], [], []],
    'recover_password' => [['email', 'token'], ['_controller' => 'App\\UserInterface\\Controller\\Security\\RecoverPasswordController'], [], [['variable', '/', '[^/]++', 'token', true], ['variable', '/', '[^/]++', 'email', true], ['text', '/handle-reset-password']], [], []],
    'logout' => [[], ['_controller' => 'App\\UserInterface\\Controller\\LogoutController'], [], [['text', '/logout']], [], []],
    'role_create' => [[], ['_controller' => 'App\\UserInterface\\Controller\\Security\\Role\\CreateController'], [], [['text', '/dashboard/role/create']], [], []],
    'user_listing' => [[], ['_controller' => 'App\\UserInterface\\Controller\\Security\\User\\ListingController'], [], [['text', '/dashboard/users']], [], []],
    'home' => [[], ['template' => 'home.html.twig', '_controller' => 'Symfony\\Bundle\\FrameworkBundle\\Controller\\TemplateController'], [], [['text', '/']], [], []],
];
